import { GoogleGenAI } from "@google/genai";

export const generateTryOn = async (
  base64Image: string,
  productDescription: string,
  category: string
): Promise<string> => {
  try {
    // Initialize inside the function to avoid top-level ReferenceError if process is not defined immediately
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    // Strip the data URL prefix if present to get just the base64 string
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');

    // Determine the target area based on the clothing category
    let targetArea = "current top/upper body clothing";
    let additionalInstructions = "";

    if (['pants', 'skirt', 'shorts', 'jeans', 'trousers'].includes(category)) {
      targetArea = "current lower body clothing (pants/skirt)";
      additionalInstructions = "Ensure the waistline blends naturally with the existing top.";
    } else if (['dress', 'suit', 'fullbody'].includes(category)) {
      targetArea = "current outfit (both top and bottom)";
    }

    const prompt = `Edit this image to show the person wearing a new outfit.
    Replace the person's ${targetArea} with: ${productDescription}.
    
    CRITICAL INSTRUCTIONS:
    1. Accurately detect the person's body, even if they are standing far away or only partially visible.
    2. Map the new clothing perfectly to their body shape, pose, and perspective.
    3. Ensure realistic fabric folds, lighting, and shadows that match the original scene.
    4. Do NOT modify the person's face, hair, skin tone, hands, or the background.
    5. ${additionalInstructions}
    
    Output a high-quality, photorealistic image.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    // Check for inline data (image) response
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData && part.inlineData.data) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};